export enum ErrorTypes {
    NOT_FOUND = 'NOT_FOUND',
    BAD_REQUEST = 'BAD_REQUEST',
    INVALID_INPUT = 'INVALID_INPUT',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    FORBIDDEN = 'FORBIDDEN',
    UNAUTHENTICATED = 'UNAUTHENTICATED',
    UNAUTHORIZED = 'UNAUTHORIZED',
    NOT_ALLOWED = 'NOT_ALLOWED',
    INTERNAL_ERROR = 'INTERAL_ERROR',
    ALREADY_EXIST= 'ALREADY_EXIST'
}